module.exports = {
  New_Project_Open_From_Computer_Demo: require("./locator.6rU6ai2YIL.json"),
  File: require("./locator.aXDf81MVGM.json"),
  New_Project: require("./locator.cf76Pl4QPx.json"),
  ".svggallery_>_:nth-child(3)_[y='132": require("./locator.jfbDY2daIt.json"),
  "[width='964']": require("./locator.j7c91LQNW5.json"),
  "Wake_Me_Up!": require("./locator.MqQb42e1ZB.json"),
  "New...": require("./locator.dg5aPyfszh.json"),
  ".svggallery_>_:nth-child(1)_[id='Ba": require("./locator.sGbMknSpKX.json"),
  Background: require("./locator.O67uflg8x6.json"),
  Learn: require("./locator.GvQj4W9IfL.json"),
  Learn_Photopea: require("./locator.2WZXxxuhhQ.json"),
  Blog: require("./locator.W3QbaRBPD9.json"),
  ".curr": require("./locator.SwZBrguNRQ.json"),
  Report_a_bug: require("./locator.ygJ8FfrpkF.json"),
  "Why_GitHub?": require("./locator.1THCxVnGxz.json"),
  API: require("./locator.DvfxPzfsUH.json"),
  Issues: require("./locator.3UQZCSt7lJ.json"),
};
