module.exports = {
  "Firefox": require('./locator.ceUeqZfDTl.json'),
  "What_were_reading:": require('./locator.mFkIYg3f86.json'),
  "Visit_the_Mozilla_Foundation": require('./locator.fNriKb949C.json'),
  "Explore_Mozilla_technology": require('./locator.9PBjHd3zBy.json'),
  "Your_email_address": require('./locator.JKT6A3kHrf.json'),
  "Learn_more_about_us": require('./locator.yVrGl92Xy8.json'),
  "Projects": require('./locator.EMFmLXXdVb.json'),
  "Common_Voice": require('./locator.236AHxO9dn.json'),
  "Firefox_Desktop_Browser_Get_the_bro": require('./locator.OB2F8zK3Wl.json'),
  "About": require('./locator.plM6t0xTwY.json'),
  "Mozilla": require('./locator.5QANsOFCzQ.json'),
  "Developers": require('./locator.qrcjO4Lhbg.json'),
  "Firefox_Developer_Edition": require('./locator.MiOCxuVg7H.json'),
};