module.exports = {
  "How_TO_-_Hide_Menu_on_Scroll": require('./locator.5ty3odAHd5.json'),
  "Next_": require('./locator.mSDJml0Zxj.json'),
  "How_TO_-_Shrink_Navigation_Menu_on_": require('./locator.yx3v7wxF6e.json'),
  "_Previous": require('./locator.Bw7WNUl2XB.json'),
  "How_TO_-_Slide_Down_a_Bar_on_Scroll": require('./locator.cdsPKQKPoV.json'),
  "[id='leftmenuinnerinner']": require('./locator.5CaolCT4Vu.json'),
  "[id='leftmenuinnerinner']_>_:nth-ch": require('./locator.lmPIXyxCUf.json'),
  "W3Schools_How_To": require('./locator.rLVMOid7k4.json'),
  "How_TO_-_Responsive_Header": require('./locator.FOUWpW1LZK.json'),
  ".searchinput": require('./locator.74hcn4d3hI.json'),
  "Slide_Down_Bar_on_Scroll": require('./locator.Lsrp8VXipA.json'),
  "Search_W3Schools": require('./locator.bF04yE2mrW.json'),
  ".gsib_a": require('./locator.uYruykP9jK.json'),
  "Custom_Search": require('./locator.SSPSE6rEoT.json'),
  "About_1,520_results_(0.20_seconds)": require('./locator.5iLSnue5oT.json'),
  ".gsc-results-close-btn": require('./locator.MxrgtlY7pS.json'),
  "No_Results": require('./locator.3c6AHokKLy.json'),
  ".gsc-search-button-v2": require('./locator.vwKbLYTdh3.json'),
  ".gscb_a": require('./locator.fg3cc7NQId.json'),
};