module.exports = {
  "40": require('./locator.ZWEbpLuZaY.json'),
  "41": require('./locator.k9rj8OL4bJ.json'),
  "Home_Footwear_White_Plimsolls": require('./locator.3aktdfFgrQ.json'),
  "$44.10": require('./locator.QC5VKDUxF1.json'),
  ".product-description__variant-picke": require('./locator.8Wmnz9S2go.json'),
  "$49.00": require('./locator.BoipxjhkCD.json'),
  "TmU3SBL8YF": require('./locator.TmU3SBL8YF.json'),
  ".sc-iSDuPN_>_:nth-child(2)_.sc-bAeI": require('./locator.UJGOHn7f4s.json'),
  "WHITE_PLIMSOLLS": require('./locator.9GEsSSFFFR.json'),
  ".sc-gqjmRU": require('./locator.lxfo65iyK9.json'),
  "ADD_TO_WISHLIST": require('./locator.ff0aSs7D5p.json'),
  "PLEASE_LOG_IN_TO_ADD_THE_PRODUCT_TO": require('./locator.CHZhxlxpRo.json'),
  "[type='number']": require('./locator.tWYnj2VX5d.json'),
  "PLEASE_SELECT_SHOE_SIZE": require('./locator.k92kSjb2rh.json'),
  "[data-src='/images/cart.svg']": require('./locator.kAgPZK5s2D.json'),
  "MY_BAG,_0_ITEMS": require('./locator.lOitLHA83d.json'),
  "[data-src='/images/x.svg']": require('./locator.XI3Bc8HPGi.json'),
  "ADD_TO_BASKET": require('./locator.2kC8HggxTa.json'),
  "SUBTOTAL_$44.10": require('./locator.Cv9mxUDOlo.json'),
  ".cart__list__item__details__delete-": require('./locator.OI9GvATuWN.json'),
  "0_ITEMS": require('./locator.jOGsRMsXSV.json'),
};