module.exports = {
  "<iframe>:_The_Inline_Frame_element": require('./locator.sKbjPs51QX.json'),
  "HTML_Demo:_<iframe>": require('./locator.tmTFWWn8lt.json'),
  "CSS": require('./locator.UTNVwRG3oe.json'),
  "1_iframe_{_2_border:_1px_solid_blac": require('./locator.jJypXWTXjF.json'),
  "+__Report_a_problem_|__OpenStreetMa": require('./locator.0r6Cw43Zhj.json'),
  "Zoom_in": require('./locator.XkheLBIu2V.json'),
  "hWVRKeVLtS": require('./locator.hWVRKeVLtS.json'),
  "[id='frame_Example2']": require('./locator.a7YeIa2P99.json'),
  "[id='mapDiv']_[tabindex='0']_>_:nth": require('./locator.OhXAlVvwg1.json'),
  "Buenos_Aires": require('./locator.RWsb8F8B6d.json'),
  "[title='Zoom_in']": require('./locator.WjOqFgN3r7.json'),
  "Zoom_out": require('./locator.G3XZBriSh4.json'),
  "OpenStreetMap": require('./locator.MMf3qcOQmU.json'),
};