module.exports = {
  Expand_All: require("./locator.FrX7i8ikC9.json"),
  ".css-151gfhx": require("./locator.t8G7XpFjno.json"),
  ".css-18uemre_>_li:nth-of-type(20)_.": require("./locator.PUxb5YXzuv.json"),
  Gatsby_REPL: require("./locator.5RhJ0ciAPc.json"),
  ".css-18uemre_>_li:nth-of-type(1)_.c": require("./locator.6kMexDhjlC.json"),
  "Gatsby.js_Documentation": require("./locator.WK1KqGsYxE.json"),
  Gatsby_Logo: require("./locator.hNYTXk6vvC.json"),
  Docs: require("./locator.hyrO7QqNz7.json"),
  Tutorial: require("./locator.HAHMZWzB1l.json"),
  Plugins: require("./locator.ntiVhTHeZj.json"),
  Features: require("./locator.sS60HkfHu7.json"),
  Blog: require("./locator.dFt5YMUA7X.json"),
  Showcase: require("./locator.usqjncGyUU.json"),
  Contributing: require("./locator.6wr73cCw9p.json"),
  "Search_gatsbyjs.org": require("./locator.BaX9ATUcF7.json"),
  "[id='doc-search']": require("./locator.n1FEVMyD4D.json"),
  Gatsby_Image_API: require("./locator.RGO1NQcTwj.json"),
  "[id='gatsby-image']": require("./locator.KsbU5vu2pS.json"),
  "No_results_found_for_query_\"jikio\"": require("./locator.KhwEPZKT5I.json"),
};
